#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

collections:
  - name: ansible.posix
    version: ">=1.6.2"
  - name: community.general
    version: ">=10.3.0"
  - name: community.docker
    version: ">=4.3.1"
  - name: containers.podman
    version: ">=1.16.2"
  - name: hyperledger.fabricx
    version: "0.5.5"
